"""rename address

Revision ID: 482590b91c20
Revises: a335b2ed1e25
Create Date: 2025-06-12 08:47:27.397557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '482590b91c20'
down_revision = 'a335b2ed1e25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
